"""contract.py -- the fixed interface between the given tools and YOUR pipeline.

Do not edit this file. detector.py and evaluate.py build a Candidate, hand it
to your ClueAnalyzer.analyze(), and expect a ClueAssessment back. Everything
in between (your stage schemas, prompts, model calls) is yours to design.

    Candidate       -- an object Stage 1 flagged, with the pixels to look at   (given -> you)
    ClueAssessment  -- your verdict on it, published on mission/clues          (you -> given)
    StageCall       -- one model call's model, tokens, latency and cost        (you -> given)

ClueAssessment holds your stage outputs as plain dicts (your_model.model_dump()),
so your schemas can have any fields you like, with two exceptions the tools
read and the planner acts on:

    relevance["relevance"]  one of RELEVANCE_LEVELS  (high / medium count as "relevant")
    decision["action"]      one of ACTIONS
    decision["search_radius_m"]  metres, required when action == "converge_search"

The search centre of a converge_search is the Candidate's position. Your code
sets it; the model never writes coordinates.
"""
import time
import uuid
from typing import List, Optional

from pydantic import BaseModel, Field, model_validator

ACTIONS = ("ignore", "log_only", "inspect_closer", "converge_search")
RELEVANCE_LEVELS = ("high", "medium", "low", "none")


def new_id():
    return uuid.uuid4().hex[:8]


class LatLon(BaseModel):
    lat: float
    lon: float


class MissingPerson(BaseModel):
    name: str
    summary: str
    age: Optional[int] = None
    clothing: List[str] = Field(default_factory=list)
    belongings: List[str] = Field(default_factory=list)
    other: List[str] = Field(default_factory=list)
    reference_image: Optional[str] = None


class MissionContext(BaseModel):
    """Who we are looking for and where. Loaded from scenario.json."""
    mission_id: str
    person: MissingPerson
    last_known_point: LatLon
    last_seen: str
    search_area: List[LatLon]
    conditions: str = ""


class Candidate(BaseModel):
    """An object Stage 1 thinks is worth a look, with the pixels to look at."""
    lat: float
    lon: float
    cv_label: str                             # detector's label, or "unknown"
    cv_confidence: float
    crop_png_b64: str                         # padded crop around the object (PNG, base64)
    context_png_b64: Optional[str] = None     # the whole camera frame, when available
    ground_m_per_px: Optional[float] = None   # real-world size of one crop pixel
    source_uav: Optional[str] = None
    candidate_id: str = Field(default_factory=new_id)
    timestamp: float = Field(default_factory=time.time)
    zoomed: bool = False                      # True once this is the closer-look view

    def without_images(self):
        return self.model_dump(exclude={"crop_png_b64", "context_png_b64"})


class StageCall(BaseModel):
    """One model call. Your ClaudeBackend.generate() returns one per call."""
    stage: str
    model: str
    input_tokens: int
    output_tokens: int
    latency_s: float
    cost_usd: float
    attempts: int = 1


class ClueAssessment(BaseModel):
    """What your pipeline returns for one Candidate, and what goes on mission/clues."""
    mission_id: str
    candidate: dict                           # Candidate.without_images()
    descriptions: List[dict]                  # your Stage 2 output(s), as dicts: 1, or 2 after a closer look
    relevance: dict                           # your Stage 3 output; must include "relevance"
    decision: dict                            # your Stage 4 output; must include "action"
    search_center: Optional[LatLon] = None    # set by code for converge_search
    calls: List[StageCall] = Field(default_factory=list)
    assessment_id: str = Field(default_factory=new_id)
    timestamp: float = Field(default_factory=time.time)

    @model_validator(mode="after")
    def _check_contract(self):
        if self.relevance.get("relevance") not in RELEVANCE_LEVELS:
            raise ValueError(f'relevance["relevance"] must be one of {RELEVANCE_LEVELS}')
        action = self.decision.get("action")
        if action not in ACTIONS:
            raise ValueError(f'decision["action"] must be one of {ACTIONS}')
        if action == "converge_search":
            if not self.decision.get("search_radius_m"):
                raise ValueError('converge_search needs decision["search_radius_m"]')
            if self.search_center is None:
                raise ValueError("converge_search needs search_center (the candidate's position)")
        return self

    @property
    def cost_usd(self):
        return sum(c.cost_usd for c in self.calls)

    @property
    def object_type(self):
        """Best-effort label for reports: your last description's object_type, if it has one."""
        return str(self.descriptions[-1].get("object_type", "?")) if self.descriptions else "?"
