FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/mavlink_lib.py .
COPY backend/drone_backend.py .

CMD ["python", "-u", "drone_backend.py"]
